---
# tasks file for ansible/roles/osint

- name: "Install dependencies"
  package:
    name: " {{ item }}"
    state: present
  with_items:
    - git-core
    - libimage-exiftool-perl

# Install Recon-ng
- name: "Install recon-ng"
  git:
    repo: "https://github.com/lanmaster53/recon-ng"
    dest: "{{ tools_path }}/recon-ng/"


- name: 'Install recon-ng requirements'
  pip:
    requirements: /opt/recon-ng/REQUIREMENTS
    state: present
    executable: pip3


- name: "Create symlink for recon-ng"
  file:
    src: "{{ tools_path }}/recon-ng/{{ item }}"
    dest: "/usr/bin/{{ item }}"
    owner: root
    group: root
    state: link
  with_items:
    - recon-ng
    - recon-cli

